src/Entity/Ritournelle.php
<?php

namespace App\Entity;

use App\Service\NoDiacritic;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\RitournelleRepository")
 * @ORM\HasLifecycleCallbacks()
 */
class Ritournelle
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=1024)
     */
    private $enigma;

    /**
     * @ORM\Column(type="string", length=1024)
     */
    private $response;

    /**
     * @ORM\Column(type="string", length=1024)
     */
    private $clue;

    /**
     * @var Game[]|ArrayCollection
     * @ORM\OneToMany(targetEntity="App\Entity\Game", mappedBy="ritournelle", orphanRemoval=true)
     */
    private $games;

    /**
     * @var bool
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $enabled = true;

    /**
     * @ORM\Column(type="date_immutable")
     */
    private $createdAt;

    /**
     * @var User
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="ritournelles")
     */
    private $user;

    public function __construct()
    {
        $this->games = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEnigma(): ?string
    {
        return $this->enigma;
    }

    public function setEnigma(string $enigma): self
    {
        $this->enigma = $enigma;

        return $this;
    }

    public function getResponse(): ?string
    {
        return $this->response;
    }

    public function setResponse(string $response): self
    {
        $this->response = $response;

        return $this;
    }

    public function getClue(): ?string
    {
        return $this->clue;
    }

    public function setClue(string $clue): self
    {
        $this->clue = $clue;

        return $this;
    }

    /**
     * @return Collection|Game[]
     */
    public function getGames(): Collection
    {
        return $this->games;
    }

    public function addGame(Game $game): self
    {
        if (!$this->games->contains($game)) {
            $this->games[] = $game;
            $game->setRitournelle($this);
        }

        return $this;
    }

    public function removeGame(Game $game): self
    {
        if ($this->games->contains($game)) {
            $this->games->removeElement($game);
            // set the owning side to null (unless already changed)
            if ($game->getRitournelle() === $this) {
                $game->setRitournelle(null);
            }
        }

        return $this;
    }

    public function getUser(): User
    {
        return $this->user;
    }

    public function setUser(User $user): Ritournelle
    {
        $this->user = $user;

        return $this;
    }

    public function isEnabled(): bool
    {
        return $this->enabled;
    }

    public function setEnabled(bool $enabled): Ritournelle
    {
        $this->enabled = $enabled;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeImmutable $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    /**
     * @ORM\PrePersist
     *
     * @throws \Exception
     */
    public function setCreatedAtValue()
    {
        $this->createdAt = new \DateTimeImmutable();
    }

    public function isValidResponse(string $response): bool
    {
        if (empty(trim($response))) {
            return false;
        }

        return 0 === strcasecmp(
                $this->clean($response),
                $this->clean($this->response)
            );
    }

    public function getRating(): ?int
    {
        if (empty($this->games)) {
            return null;
        }
        $rating = 0;
        $nbResults = 0;
        foreach ($this->games as $game) {
            $results = $game->getResults();
            $nbResults += $results->count();
            foreach ($results as $result) {
                $rating += $result->getRating();
            }
        }
        if (0 == $nbResults) {
            return null;
        }

        return ceil($rating / $nbResults);
    }

    public function getLastRating(): ?int
    {
        $lastGame = $this->getLastGame();
        if (empty($lastGame)) {
            return null;
        }
        $results = $lastGame->getResults();
        if (0 == $results->count()) {
            return null;
        }
        $rating = 0;
        foreach ($results as $result) {
            $rating += $result->getRating();
        }

        return ceil($rating / $results->count());
    }

    private function getLastGame(): ?Game
    {
        /** @var Game|null $lastGame */
        $lastGame = null;
        if (empty($this->games)) {
            return $lastGame;
        }
        foreach ($this->games as $game) {
            if (empty($lastGame) || $lastGame->getPlayedAt() < $game->getPlayedAt()) {
                $lastGame = $game;
            }
        }

        return $lastGame;
    }

    /**
     * On renvoie la moitié des mots aléatoirement.
     */
    public function getRandomHalfWords(): array
    {
        $randomWords = [];
        $words = explode(' ', $this->response);
        $nbWords = floor(count($words) / 2);

        $safeguard = 100;
        for ($i = 0; $i < $nbWords && $safeguard > 0; ++$i) {
            $randomWord = $words[array_rand($words)];
            if (in_array($randomWord, $randomWords)) {
                --$i;
                --$safeguard;
                continue;
            }
            $randomWords[] = $randomWord;
        }

        return $randomWords;
    }

    public function getSimilarity(string $trial): float
    {
        similar_text(
            $this->clean($trial),
            $this->clean($this->response),
            $percent);

        return $percent;
    }

    private function clean(string $text): string
    {
        return trim(preg_replace('/[\'"´’.,;:\/\!§%$£*¤"#\'`\(){}+=@&]/', '', NoDiacritic::filter($text)));
    }
}

src/Controller/RitournelleController.php
<?php

namespace App\Controller;

use App\Entity\CustomResult;
use App\Entity\CustomRitournelle;
use App\Entity\Game;
use App\Entity\Response as ResponseGame;
use App\Entity\Result;
use App\Entity\Ritournelle;
use App\Entity\User;
use App\Form\CommentType;
use App\Form\CustomResponseType;
use App\Form\CustomRitournelleType;
use App\Form\ResponseType;
use App\Form\RitournelleType;
use App\Repository\CustomRitournelleRepository;
use App\Repository\GameRepository;
use App\Repository\ResultRepository;
use App\Repository\RitournelleRepository;
use App\Service\GameManager;
use DateTimeImmutable;
use Doctrine\ORM\EntityManagerInterface;
use Exception;
use Psr\Log\LoggerInterface;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/ritournelle", name="ritournelle_")
 */
class RitournelleController extends AbstractController
{
    /**
     * @Route("/enigma", name="enigma")
     *
     * @return Response
     *
     * @throws Exception
     */
    public function enigma(
        EntityManagerInterface $em,
        GameManager $gameManager,
        Request $request
    ) {
        /** @var User $user */
        $user = $this->getUser();

        $game = $gameManager->getTodaysGame();
        $ritournelle = $game->getRitournelle();

        /** @var ResultRepository $resultRepo */
        $resultRepo = $em->getRepository(Result::class);
        $result = $resultRepo->findTodayResult($user, $game);
        $results = $game->getResults();

        $customRitournelleFormView = $previousRitournelle = null;

        // on cherche les informations pour les customs ritournelles
        $previousGame = $gameManager->getPreviousGame();
        if ($previousGame) {
            $previousRitournelle = $previousGame->getRitournelle();
        }
        /** @var CustomRitournelleRepository $customRitournelleRepo */
        $customRitournelleRepo = $em->getRepository(CustomRitournelle::class);
        $customRitournelle = $customRitournelleRepo->findOneBy(['user' => $user, 'createdAt' => new DateTimeImmutable('today')]);
        if (!$customRitournelle) {
            $customRitournelle = new CustomRitournelle();
            $customRitournelleForm = $this->createForm(CustomRitournelleType::class, $customRitournelle);
            $customRitournelleForm->handleRequest($request);
            if ($customRitournelleForm->isSubmitted() && $customRitournelleForm->isValid()) {
                if (empty($result)) {
                    $this->addFlash('success', 'success.defy_ritournelle_waiter');
                } else {
                    $this->addFlash('success', 'success.defy_ritournelle_winner');
                }
                $customRitournelle->setUser($user);
                $em->persist($customRitournelle);
                $em->flush();

                return $this->redirectToRoute('ritournelle_enigma');
            }
            // On n'envoie pas le formulaire si une ritournelle a déjà été envoyée
            $customRitournelleFormView = $customRitournelleForm->createView();
        }
        $customResults = $customRitournelle->getCustomResults();

        // On récupère les ritournelles des autres
        $customRitournelleOthers = $customRitournelleRepo->findOthers(new DateTimeImmutable('today'), $user);
        $customOthers = [];
        $hasNewCustomRitournelle = false;
        foreach ($customRitournelleOthers as $customRitournelleOther) {
            $customOther = [];
            $customOther['ritournelle'] = $customRitournelleOther;
            $customOther['result'] = $customRitournelleOther->getCustomResult($user) ?? '';
            $customOther['form'] = '';

            if (empty($customOther['result'])) {
                $customResponse = new \stdClass();
                $customResponse->customRitournelle = $customRitournelleOther;
                $customResponse->response = '';
                $customResponseForm = $this->createForm(CustomResponseType::class, $customResponse);

                $customResponseForm->handleRequest($request);
                if ($customResponse->customRitournelle === $customRitournelleOther && $customResponseForm->isSubmitted() && $customResponseForm->isValid()) {
                    // on vérifie si la réponse donnée correspond à celle de la ritournelle
                    if ($customRitournelleOther->isValidResponse($customResponse->response)) {
                        // On enregistre en BDD que la réponse a été trouvé
                        $customResult = new CustomResult();
                        $customResult->setUser($user);
                        $customResult->setCustomRitournelle($customRitournelleOther);
                        $em->persist($customResult);
                        $em->flush();

                        // On indique que la réponse en juste
                        $this->addFlash('success', 'ritournelle.right_custom_response');

                        return $this->redirectToRoute('ritournelle_enigma');
                    } else {
                        // on indique que la réponse est fausse
                        $this->addFlash('danger', 'ritournelle.wrong_custom_response');
                    }
                }
                $customResponse->customRitournelle = $customRitournelleOther;
                $customResponse->response = '';
                $customResponseForm = $this->createForm(CustomResponseType::class, $customResponse);
                $customOther['form'] = $customResponseForm->createView();
                $hasNewCustomRitournelle = true;
            }
            $customOthers[] = $customOther;
        }

        // Si la personne n'a toujours pas trouvé, on regarde si elle a soumis le formulaire
        $response = new \stdClass();
        $response->enigma = $ritournelle->getEnigma();
        $response->response = '';
        $responseForm = $this->createForm(ResponseType::class, $response);
        if (empty($result)) {
            $responseForm->handleRequest($request);
            if ($responseForm->isSubmitted() && $responseForm->isValid()) {
                // on vérifie si la réponse donnée correspond à celle de la ritournelle
                if ($ritournelle->isValidResponse($response->response)) {
                    // On enregistre en BDD que la réponse a été trouvé
                    $result = $resultRepo->save($game, $user);
                    // on ajoute à la liste
                    $results[] = $result;

                    // On indique que la réponse en juste
                    $this->addFlash('success', 'ritournelle.right_response');

                    // On va vers un affichage qui gère l'ajout d'un commentaire
                    return $this->redirectToRoute('ritournelle_comment');
                } else {
                    $responseGame = new ResponseGame();
                    $responseGame->setGame($game);
                    $responseGame->setUser($user);
                    $responseGame->setResponse($response->response);

                    $em->persist($responseGame);
                    $em->flush();
                }

                // On indique que la réponse est fausse
                $this->addFlash('danger', 'ritournelle.wrong_response');
            }
        }
        $responseFormView = $responseForm->createView();

        // On récupère le classement de la semaine en cours
        $firstCurrentWeek = $gameManager->getFirstCurrentWeek();
        $secondCurrentWeek = $gameManager->getSecondCurrentWeek();
        $thirdCurrentWeek = $gameManager->getThirdCurrentWeek();
        $othersCurrentWeek = $gameManager->getOthersCurrentWeek();

        return $this->render(
            'ritournelle/enigma.html.twig',
            compact(
                'customOthers',
                'customResults',
                'customRitournelle',
                'customRitournelleFormView',
                'game',
                'previousRitournelle',
                'responseFormView',
                'result',
                'results',
                'ritournelle',
                'hasNewCustomRitournelle',
                'firstCurrentWeek',
                'secondCurrentWeek',
                'thirdCurrentWeek',
            )
        );
    }

    /**
     * @Route("/comment", name="comment")
     *
     * @return Response
     *
     * @throws Exception
     */
    public function commentResult(
        EntityManagerInterface $em,
        GameManager $gameManager,
        LoggerInterface $logger,
        Request $request
    ) {
        /** @var User $user */
        $user = $this->getUser();
        /** @var GameRepository $gameRepo */
        $gameRepo = $em->getRepository(Game::class);
        $game = $gameManager->getTodaysGame();

        /** @var ResultRepository $resultRepo */
        $resultRepo = $em->getRepository(Result::class);
        $result = $resultRepo->findTodayResult($user, $game);
        $results = $resultRepo->findByGame($game);

        if (!$result) {
            return $this->redirectToRoute('ritournelle_enigma');
        }

        $comment = new \stdClass();
        $comment->comment = $result->getComment();
        $comment->rating = $rating = $result->getRating() ?? Result::RATING_DEFAULT;
        $comment->comment_ritournelle = $result->getCommentRitournelle();
        $comment->acceptedWarn = $user->isAcceptedWarn();

        $commentForm = $this->createForm(CommentType::class, $comment);

        $commentForm->handleRequest($request);
        if ($commentForm->isSubmitted() && $commentForm->isValid()) {
            $result->setComment($comment->comment);
            $result->setRating($comment->rating);
            $result->setCommentRitournelle($comment->comment_ritournelle);
            if (!$user->isAcceptedWarn()) {

templates/ritournelle/inc/defy.html.twig
{% trans_default_domain 'ritournelle' %}
<div class="card">
    <div class="card-header" id="headingOne">
        <h5 class="mb-0">
            <button class="btn btn-link" data-toggle="collapse"
                    data-target="#collapseDefy" aria-expanded="true"
                    aria-controls="collapseDefy">
                {{ 'ritournelle.defy_title'|trans }}{% if not customRitournelleFormView %} - {{ 'ritournelle.defy.found'|trans({'nb': customResults|length}) }}{% endif %}
            </button>
        </h5>
    </div>

    <div id="collapseDefy"
         class="collapse {% if customRitournelleFormView and not hasNewCustomRitournelle %}show{% else %}hide{% endif %}"
         aria-labelledby="headingDefy"
         data-parent="#accordion">
        <div class="card-body">
            {% if customRitournelleFormView %}
                {{ form_start(customRitournelleFormView) }}
                <div class="form-group">
                    {{ form_label(customRitournelleFormView.enigma) }}
                    {{ form_widget(customRitournelleFormView.enigma) }}
                </div>
                <div class="form-group">
                    {{ form_label(customRitournelleFormView.response) }}
                    {{ form_widget(customRitournelleFormView.response) }}
                </div>
                <div class="form-group">
                    {{ form_label(customRitournelleFormView.clue) }}
                    {{ form_widget(customRitournelleFormView.clue) }}
                </div>
                {{ form_widget(customRitournelleFormView.save) }}
                {{ form_end(customRitournelleFormView) }}
            {% else %}
                <div class="container-lg">
                    <div class="row" style="height: 150px">
                        <div class="col-6">
                            <p>
                                {{ 'ritournelle.yours'|trans }}
                            </p>
                            <h5 class="card-title">{{ customRitournelle.enigma }}</h5>
                            <h6 class="card-subtitle mb-2 text-muted">{{ customRitournelle.response }}</h6>
                            <p class="card-text">{{ 'ritournelle.clue'|trans }}
                                :<br>{{ customRitournelle.clue }}</p>
                        </div>
                        <div class="col-6 mh-100" style="overflow-y: scroll;">
                            <ul class="list-group">
                                {% for customResult in customResults %}
                                    <li class="list-group-item list-group-item-action">
                                        {{ 'ritournelle.user_found'|trans({'user':customResult.user.username, 'time': customResult.replyAt|date("H") ~ 'h' ~ customResult.replyAt|date("i")}) }}
                                    </li>
                                {% else %}
                                    <p>
                                        {{ 'ritournelle.custom_not_found'|trans }}
                                    </p>
                                {% endfor %}
                            </ul>
                        </div>
                    </div>
                </div>
            {% endif %}
        </div>
    </div>
</div>

templates/ritournelle/inc/points.html.twig
{#
<div class="d-flex justify-content-start alert alert-light" role="alert">
    <div class="p-2">points à prendre :</div>
    <div class="p-2 mr-2 ml-2 bg-warning text-white" style="border-radius: 50%;background: green; width: 2.5rem; height: 2.5rem; text-align: center">10</div>
    <div class="p-2 mr-2 ml-2 bg-warning text-white" style="border-radius: 50%;background: green; width: 2.5rem; height: 2.5rem; text-align: center">8</div>
    <div class="p-2 mr-2 ml-2 bg-warning text-white" style="border-radius: 50%;background: green; width: 2.5rem; height: 2.5rem; text-align: center">6</div>
    <div class="p-2 mr-2 ml-2 bg-warning text-white" style="border-radius: 50%;background: green; width: 2.5rem; height: 2.5rem; text-align: center">4</div>
    <div class="p-2 mr-2 ml-2 bg-warning text-white" style="border-radius: 50%;background: green; width: 2.5rem; height: 2.5rem; text-align: center">2</div>
</div>
#}

templates/ritournelle/inc/previous.html.twig
{% trans_default_domain 'ritournelle' %}
<div class="card">
    <div class="card-header" id="headingOne">
        <h5 class="mb-0">
            <button class="btn btn-link" data-toggle="collapse"
                    data-target="#collapsePrevious" aria-expanded="true"
                    aria-controls="collapsePrevious">
                {{ 'ritournelle.previous'|trans }}
            </button>
        </h5>
    </div>

    <div id="collapsePrevious"
         class="collapse hide"
         aria-labelledby="headingPrevious"
         data-parent="#accordion">
        <div class="card-body">
            <label>{{ 'ritournelle.enigma'|trans }}</label>
            {% set rating = previousRitournelle.lastRating|default(null) %}
            {% if rating > 0 %}
                {% include 'ritournelle/inc/rating.html.twig' with {'disabled': true} %}
            {% endif %}
            <h5 class="card-title">{{ previousRitournelle.enigma|default('') }}</h5>
            <button class="btn btn-secondary" type="button"
                    data-toggle="collapse"
                    data-target="#collapseClue"
                    aria-expanded="false"
                    aria-controls="collapseExample">
                {{ 'ritournelle.show_clue'|trans }}
            </button>
            <div class="collapse"
                 id="collapseClue">
                <p class="mt-2 card-text">
                    {{ previousRitournelle.clue|default('') }}
                </p>
            </div>
            <br>
            <button class="btn btn-secondary mt-2" type="button"
                    data-toggle="collapse"
                    data-target="#collapseResponse"
                    aria-expanded="false"
                    aria-controls="collapseExample">
                {{ 'ritournelle.show_response'|trans }}
            </button>
            <div class="collapse"
                 id="collapseResponse">
                <p class="mt-2 card-text">
                    {{ previousRitournelle.response|default('')|escape }}
                </p>
            </div>
        </div>
    </div>
</div>

templates/ritournelle/inc/rating.html.twig
{% trans_default_domain 'ritournelle' %}

<div class="star-rating">
    <input id="star-5" type="radio" name="comment[rating]" value="5" {% if rating == 5 %}checked{% endif %} {% if disabled %}disabled{% endif %}/>
    <label for="star-5" title="{{ 'ritournelle.level5'|trans }}">
        <i class="active fas fa-star" aria-hidden="true"></i>
    </label>
    <input id="star-4" type="radio" name="comment[rating]" value="4"  {% if rating == 4 %}checked{% endif %} {% if disabled %}disabled{% endif %}/>
    <label for="star-4" title="{{ 'ritournelle.level4'|trans }}">
        <i class="active fas fa-star" aria-hidden="true"></i>
    </label>
    <input id="star-3" type="radio" name="comment[rating]" value="3"  {% if rating == 3 %}checked{% endif %} {% if disabled %}disabled{% endif %}/>
    <label for="star-3" title="{{ 'ritournelle.level3'|trans }}">
        <i class="active fas fa-star" aria-hidden="true"></i>
    </label>
    <input id="star-2" type="radio" name="comment[rating]" value="2" {% if rating == 2 %}checked{% endif %} {% if disabled %}disabled{% endif %}/>
    <label for="star-2" title="{{ 'ritournelle.level2'|trans }}">
        <i class="active fas fa-star" aria-hidden="true"></i>
    </label>
    <input id="star-1" type="radio" name="comment[rating]" value="1" {% if rating == 1 %}checked{% endif %} {% if disabled %}disabled{% endif %}/>
    <label for="star-1" title="{{ 'ritournelle.level1'|trans }}">
        <i class="active fas fa-star" aria-hidden="true"></i>
    </label>
</div>
<style>
    .star-rating {
        direction: rtl;
        display: inline-block;
    }

    .star-rating input[type=radio] {
        display: none
    }

    .star-rating label {
        color: #bbb;
        font-size: 18px;
        padding: 0;
        cursor: pointer;
        -webkit-transition: all .3s ease-in-out;
        transition: all .3s ease-in-out
    }

    {% if not disabled %}
    .star-rating label:hover,
    .star-rating label:hover ~ label,{% endif %}
    .star-rating input[type=radio]:checked ~ label {
        color: #f2b600
    }
</style>

templates/ritournelle/inc/ritournelleStatic.html.twig
{% trans_default_domain 'ritournelle' %}

{{ form_label(responseFormView.enigma) }}
{{ form_widget(responseFormView.enigma) }}
{% if hour >= hour_clue %}
    <p class="lead mt-2">
        {{ 'ritournelle.clue.label'|trans({'clue': ritournelle.clue}) }}
    </p>
{% endif %}
<p class="lead mt-3">
    {{ 'ritournelle.given_response'|trans({'response': ritournelle.response|escape})|raw }}
</p>

templates/ritournelle/inc/winner.html.twig
{% trans_default_domain 'ritournelle' %}

<div class="col-3">
    <h5>{{ 'ritournelle.list_user_result'|trans }}</h5>
    <ul class="list-group">
        {% for result_user in results %}
            <li class="list-group-item list-group-item-action">
                <div class="d-flex justify-content-between">
                    {% if result_user.user.id in firstCurrentWeek|keys %}
                        <img src="{{ asset('img/medals/medalgold.svg') }}" class="mr-1"
                             style="height: 1.5rem;width: auto;"/>
                    {% elseif result_user.user.id in secondCurrentWeek|keys %}
                        <img src="{{ asset('img/medals/medalsilver.svg') }}" class="mr-1"
                             style="height: 1.5rem;width: auto;"/>
                    {% elseif result_user.user.id in thirdCurrentWeek|keys %}
                        <img src="{{ asset('img/medals/medalbronze.svg') }}" class="mr-1"
                             style="height: 1.5rem;width: auto;"/>
                    {% endif %}
                    <div>
                        {{ 'ritournelle.user_found'|trans({'user':result_user.user.username, 'time': result_user.replyAt|date("H") ~ 'h' ~ result_user.replyAt|date("i")}) }}
                    </div>
                    <div>
                        <a href="{{ path('game_classement') }}" class="text-secondary"><small>{{ 'ritournelle.user_points'|trans({'points':result_user.point})|raw }}</small></a>
                    </div>
                </div>
                <blockquote class="blockquote text-right mt-2">
                    <p class="mb-0 text-truncate" data-toggle="tooltip" data-placement="left" title="{{ result_user.comment }}">
                        {{ result_user.comment }}
                    </p>
                </blockquote>
                {% if app.user == result_user.user %}
                    <a href="{{ path('ritournelle_comment') }}">{{ 'ritournelle.edit'|trans }}</a>
                {% endif %}
            </li>
        {% else %}
            {{ 'ritournelle.no_result'|trans|raw }}
        {% endfor %}
    </ul>
</div>